from utils.anthropic_client import AnthropicClient
import json
from typing import List, Dict, Optional
import re
from sqlalchemy.ext.asyncio import AsyncSession
from models.topic_recommendation import TopicRecommendation


class TopicDiscoveryService:
    """AI-powered topic discovery service"""

    def __init__(self, db: Optional[AsyncSession] = None):
        self.client = AnthropicClient()
        self.db = db

    async def discover(
        self,
        field: str,
        keywords: List[str],
        topic: str = None,
        description: str = None,
        num_suggestions: int = 5
    ) -> Dict:
        """
        使用 AI 推荐研究选题

        Args:
            field: 研究领域
            keywords: 关键词列表
            topic: 具体研究主题/细分方向 (可选)
            description: 研究方向描述 (可选)
            num_suggestions: 推荐数量，默认 5

        Returns:
            包含 suggestions 列表的字典
        """

        # 构建上下文
        context = f"研究领域: {field}\n"
        if topic:
            context += f"具体主题/细分方向: {topic}\n"
        context += f"关键词: {', '.join(keywords)}"

        if description:
            context += f"\n研究方向描述: {description}"

        # 构建任务
        task = f"请针对上述研究领域"
        if topic:
            task += f"中的 '{topic}' 这一具体主题"
        task += f"，推荐 {num_suggestions} 个创新且可行的研究选题，严格按照 JSON 格式输出。"

        # 调用 AI
        response_text = await self.client.create_message(
            role="topic_discovery_expert",
            context=context,
            task=task
        )

        # 1. Extract Signature
        signature = None
        cleaned_response = response_text
        lines = response_text.strip().split('\n')
        if lines:
            last_line = lines[-1].strip()
            if last_line.startswith("-- Generated by") and last_line.endswith("--"):
                signature = last_line
                cleaned_response = '\n'.join(lines[:-1]).strip()

        if not signature:
            signature = f"-- Generated by {self.client.model} (Fallback) --"

        # 解析 JSON
        try:
            # 尝试直接解析
            result = json.loads(cleaned_response)
        except json.JSONDecodeError:
            # 尝试提取 JSON 部分（处理 AI 可能在 JSON 前后添加说明文字的情况）
            json_match = re.search(r'\{.*\}', cleaned_response, re.DOTALL)
            if json_match:
                try:
                    result = json.loads(json_match.group())
                except json.JSONDecodeError:
                    raise ValueError(f"AI 返回格式错误，无法解析为有效 JSON。原始响应: {cleaned_response[:200]}...")
            else:
                raise ValueError(f"AI 返回格式错误，无法解析为有效 JSON。原始响应: {cleaned_response[:200]}...")

        # Add signature to result for frontend display
        result['model_signature'] = signature

        # 保存推荐历史到数据库
        if self.db:
            try:
                recommendation = TopicRecommendation(
                    research_field=field,
                    specific_topic=topic,
                    keywords=json.dumps(keywords, ensure_ascii=False),
                    description=description,
                    suggestions=json.dumps(result.get('suggestions', []), ensure_ascii=False),
                    model_signature=signature
                )
                self.db.add(recommendation)
                await self.db.commit()
                await self.db.refresh(recommendation)

                # 添加历史记录 ID 到返回结果
                result['recommendation_id'] = recommendation.id
            except Exception as e:
                # 记录错误但不影响推荐结果返回
                print(f"Warning: Failed to save recommendation history: {e}")
                await self.db.rollback()

        return result
