import React, { useEffect, useState } from 'react'
import { useDispatch, useSelector } from 'react-redux'
import { Timeline, Card, Tag, Typography, Spin, Empty, Button, Drawer, Descriptions, Badge, Space } from 'antd'
import { ClockCircleOutlined, RobotOutlined, UserOutlined, FileSearchOutlined, EyeOutlined } from '@ant-design/icons'
import ReactMarkdown from 'react-markdown'
import type { RootState, AppDispatch } from '@/store/store'
import { fetchPaperTrace, PaperTraceItem } from '@/store/slices/papersSlice'

const { Title, Text, Paragraph } = Typography

interface PaperTraceProps {
  paperId: number | null
}

const agentRoleColors: Record<string, string> = {
  research_director: 'purple',
  literature_researcher: 'blue',
  methodology_expert: 'cyan',
  data_analyst: 'green',
  paper_writer: 'orange',
  peer_reviewer: 'red',
  paper_revisor: 'geekblue'
}

const agentRoleNames: Record<string, string> = {
  research_director: '研究主管',
  literature_researcher: '文献调研员',
  methodology_expert: '方法论专家',
  data_analyst: '数据分析师',
  paper_writer: '论文撰写员',
  peer_reviewer: '同行评审员',
  paper_revisor: '论文修改员'
}

const PaperTrace: React.FC<PaperTraceProps> = ({ paperId }) => {
  const dispatch = useDispatch<AppDispatch>()
  const { paperTrace, traceLoading } = useSelector((state: RootState) => state.papers)
  const [selectedItem, setSelectedItem] = useState<PaperTraceItem | null>(null)
  const [drawerVisible, setDrawerVisible] = useState(false)

  useEffect(() => {
    if (paperId) {
      dispatch(fetchPaperTrace(paperId))
    }
  }, [paperId, dispatch])

  if (!paperId) {
    return <Empty description="请先选择或生成一篇论文以查看过程回放" />
  }

  const handleViewDetail = (item: PaperTraceItem) => {
    setSelectedItem(item)
    setDrawerVisible(true)
  }

  return (
    <div style={{ padding: 24 }}>
      <Spin spinning={traceLoading}>
        <div style={{ display: 'flex' }}>
          {/* 左侧时间轴 */}
          <div style={{ width: '40%', paddingRight: 24, borderRight: '1px solid #f0f0f0' }}>
            <Title level={4} style={{ marginBottom: 24 }}>生成过程时间轴</Title>
            <Timeline mode="left">
              {paperTrace.map((item) => (
                <Timeline.Item
                  key={item.id}
                  label={new Date(item.created_at).toLocaleTimeString()}
                  dot={
                    <RobotOutlined style={{ fontSize: '16px', color: agentRoleColors[item.agent_role] || 'blue' }} />
                  }
                >
                  <Card
                    size="small"
                    hoverable
                    onClick={() => handleViewDetail(item)}
                    style={{
                      cursor: 'pointer',
                      borderLeft: `4px solid ${item.step_name?.includes('Revision') ? '#faad14' : '#1890ff'}`
                    }}
                  >
                    <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
                      <div>
                        <Text strong>{item.step_name || 'Processing'}</Text>
                        <div style={{ marginTop: 4 }}>
                          <Tag color={agentRoleColors[item.agent_role]}>
                            {agentRoleNames[item.agent_role] || item.agent_role}
                          </Tag>
                        </div>
                      </div>
                      <Button type="link" size="small" icon={<EyeOutlined />} />
                    </div>
                    {item.model_signature && (
                      <div style={{ marginTop: 8, fontSize: 12, color: '#8c8c8c' }}>
                        {item.model_signature.replace(/-- Generated by | --/g, '')}
                      </div>
                    )}
                  </Card>
                </Timeline.Item>
              ))}
            </Timeline>
          </div>

          {/* 右侧详情预览 (默认显示最新的或选中的) */}
          <div style={{ width: '60%', paddingLeft: 24 }}>
             <Empty description="点击左侧时间轴查看详细交互内容" image={Empty.PRESENTED_IMAGE_SIMPLE} />
          </div>
        </div>

        {/* 详情抽屉 */}
        <Drawer
          title={
            <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', width: '100%' }}>
              <Space>
                 <RobotOutlined />
                 <span>{selectedItem?.step_name}</span>
                 <Tag color={selectedItem ? agentRoleColors[selectedItem.agent_role] : 'default'}>
                    {selectedItem ? (agentRoleNames[selectedItem.agent_role] || selectedItem.agent_role) : ''}
                 </Tag>
              </Space>
              {selectedItem?.model_signature && (
                 <Tag icon={<UserOutlined />} color="gold">
                    {selectedItem.model_signature.replace(/-- | --/g, '')}
                 </Tag>
              )}
            </div>
          }
          width={720}
          onClose={() => setDrawerVisible(false)}
          open={drawerVisible}
        >
          {selectedItem && (
            <div>
              <Descriptions column={1} bordered size="small">
                <Descriptions.Item label="执行时间">
                  {new Date(selectedItem.created_at).toLocaleString()}
                </Descriptions.Item>
                <Descriptions.Item label="轮次">
                  Round {selectedItem.iteration}
                </Descriptions.Item>
              </Descriptions>

              <div style={{ marginTop: 24 }}>
                <Title level={5}>📥 输入指令 (Input Context)</Title>
                <div style={{
                  background: '#f5f5f5',
                  padding: 12,
                  borderRadius: 4,
                  border: '1px solid #d9d9d9',
                  maxHeight: 200,
                  overflow: 'auto',
                  fontFamily: 'monospace'
                }}>
                  {selectedItem.input_context || "无输入上下文"}
                </div>
              </div>

              <div style={{ marginTop: 24 }}>
                <Title level={5}>📤 输出结果 (Output Content)</Title>
                <div style={{
                  border: '1px solid #d9d9d9',
                  borderRadius: 4,
                  padding: 16,
                  minHeight: 200
                }}>
                  <ReactMarkdown>{selectedItem.output_content}</ReactMarkdown>
                </div>
              </div>
            </div>
          )}
        </Drawer>
      </Spin>
    </div>
  )
}

export default PaperTrace
