
import requests
import json

url = "http://127.0.0.1:8001/api/v1/industry/"
headers = {"Content-Type": "application/json"}

# Mimic the payload from frontend
payload = {
    "title": "Test Industry News",
    "source": "TechCrunch",
    "url": "https://example.com",
    "content": "This is a test content from deep research.",
    "keywords": ["AI", "Testing"],
    "relevance_score": 0.95,
    "published_at": "2024-01-30",
    "model_signature": "-- Generated by Test --",
    "topic_id": 16 # Assuming topic 16 exists or use None
}

try:
    print(f"Sending POST to {url}...")
    print(f"Payload: {json.dumps(payload, ensure_ascii=False, indent=2)}")
    response = requests.post(url, json=payload, headers=headers)
    
    print(f"Status Code: {response.status_code}")
    print("Response:", response.text)
    
except Exception as e:
    print(f"Error: {e}")
